#+title:  moo 無 model oriented objects
#+EXPORT_FILE_NAME: index.html
#+subtitle: Model Oriented Objects
#+setupfile: setup.org

* Overview
  :PROPERTIES:
  :CUSTOM_ID: overview
  :END:

*moo* is a tool for managing data structures.  *moo* operates on:

- schema :: data structures describing the structure of data (including schema).

- model :: data structure matching schema to a template.

- templates :: marked up text in some target format which is parameterized by a model and from which a document (eg, C++ code file) may be generated.

- codegen :: generated artifacts

* Version
  :PROPERTIES:
  :CUSTOM_ID: version
  :END:

The current *moo* version is

#+begin_src shell :exports both :results output code :wrap "example"
  moo version
#+end_src

#+RESULTS:
#+begin_example
0.1.0
#+end_example



* Installation
  :PROPERTIES:
  :CUSTOM_ID: install
  :END:

*moo* requires Python 3.5 or newer and ~python~ below is assumed to
provide that.

*moo* installs in to your favorite Python environment in most of the
usual ways.  Some examples are given below.  Due to a name conflict
(this) *moo* is not expected to be distributed through PyPI.

** Install a release

#+begin_example
  $ python -m pip install https://github.com/brettviren/moo/archive/0.1.0.tar.gz
#+end_example

** Install development

Just install:

#+begin_example
  $ python -m pip install git+git://github.com/brettviren/moo.git#egg=moo
#+end_example

Or, to allow working on the code:

#+begin_example
  $ git clone https://github.com/brettviren/moo.git
  $ cd moo
  $ pyton -m pip install -e .
#+end_example

* Quick start
  :PROPERTIES:
  :CUSTOM_ID: punt
  :END:

The *moo* command line interface provides various commands and online
help:

#+begin_example
  $ moo --help
#+end_example

See documentation section for details.

* Documentation
  :PROPERTIES:
  :CUSTOM_ID: docs
  :END:

- https://brettviren.github.io/moo

- [[https://github.com/brettviren/moo][code repository]] and its [[file:README.org][README]] 

- [[file:moo.org][moo high level documentation]]

- [[file:oschema.org][moo object schema paradigm]]

- [[file:otypes.org][moo object types]]

- [[file:buildsys.org][moo and build systems]]

- [[file:wcup.org][moo as Wire-Cell user package generator]]

- [[file:reqs.org][moo for LaTeX and spreadsheet generator]]

