#+title: Wire-Cell User Package Generator
#+subtitle: ~moo~ 無 ~wcup~

#+setupfile: setup.org

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: intro
  :END:

The Wire-Cell Toolkit supports "user packages" (WCUP).  A WCUP is like
a "vertical slice" of the main ~wire-cell-toolkit~ repository in that it
contains a main `wscript` and a "sub-package" directory.

The [[file:wcup/][wcup]] directory in moo provides templates and other support to
generate your own WCUP starting point.

WCUP also provides an example of the use of ~moo render-many~.

* Usage
  :PROPERTIES:
  :CUSTOM_ID: usage
  :END:


#+begin_example
  $ moo  -T wcup render-many -o ~/dev/pcbro wcup/pcbraw.jsonnet
  $ cd ~/dev/pcbro
  $ git init && git add * && git commmit -am "First commit"
  $ cp /path/to/wire-cell-toolkit/wcb .
  $ ./wcb configure --with-wct=/path/to/wct/install [...]
  $ ./wcb 
#+end_example

The developer may then start adding in more code and files.

* Caution
  :PROPERTIES:
  :CUSTOM_ID: caution
  :END:


There is *no* protection against overwriting existing files.  ~moo~ will
happily regenerate the initial skeleton files even if you have poured
your heart into developing them manually.  


